crash:
  - RomanPudashkin
  - DmitryArefiev
  - zacjansheski
engraving:
  - mike-spa
VST:
  - RomanPudashkin
"MuseSounds":
  - matthewreadbass
playback:
  - RomanPudashkin
cloud:
  - shoogle
  - cbjeukendrup
