crash:
  - RomanPudashkin
  - DmitryArefiev
  - zacjansheski
engraving:
  - mike-spa
VST:
  - RomanPudashkin
"MuseSounds":
  - matthewreadbass
  - sampleeditor
playback:
  - RomanPudashkin
cloud:
  - bkunda
  - shoogle
  - Eism