# clone directory
clone_folder: C:\MuseScore

# set clone depth
clone_depth: 50                      # clone entire repository history if not defined

image: Visual Studio 2017

branches:
  only:
  - master

# build cache to preserve files/folders between builds
cache:
  - dependencies.7z
  - qt598_msvc2017_64.7z # if not using AppVeyor's built-in Qt in before_build.bat
  - qt598_msvc2015.7z # if not using AppVeyor's built-in Qt in before_build.bat
  - C:\Program Files (x86)\Jack
  - C:\MuseScore\build.release\thirdparty
  - C:\ccache

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
#use for releases only
#  - x86
  - x64

#environment:

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# Stop Appveyor from "Discovering Tests"
test: off

matrix:
  fast_finish: true # stop all jobs if any job fails
  #allow_failures: # list jobs allowed to fail without stopping the rest

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - IF DEFINED ENCRYPT_SECRET_SSH (
    nuget install secure-file -ExcludeVersion &&
    secure-file\tools\secure-file -decrypt C:\MuseScore\build\appveyor\resources\osuosl_nighlies_rsa_nopp.enc -secret %ENCRYPT_SECRET_SSH%
    )
  - IF DEFINED ENCRYPT_SECRET_CERTIFICATE (
    nuget install secure-file -ExcludeVersion &&
    secure-file\tools\secure-file -decrypt C:\MuseScore\build\appveyor\resources\musescore.p12.enc -secret %ENCRYPT_SECRET_CERTIFICATE%
    )

# scripts to run before build
before_build:
  - cmd: C:\MuseScore\build\appveyor\before_build.bat

build_script:
  - cmd: C:\MuseScore\build\appveyor\build_script.bat

after_build:
  - cmd: C:\MuseScore\build\appveyor\after_build.bat

on_success:
  - ps: |
        if ($env:APPVEYOR_PULL_REQUEST_NUMBER -eq $null -or ($env:APPVEYOR_PULL_REQUEST_NUMBER -ne $null -and $env:APPVEYOR_REPO_COMMIT_MESSAGE -like "*collect_artifacts*"))
        {
            Push-AppveyorArtifact $env:ARTIFACT_NAME -deploymentname musescore-binary
            Push-AppveyorArtifact $env:DEBUG_SYMS_FILE -deploymentname musescore-dbg-info.sym
            Push-AppveyorArtifact update_win_nightly.xml
            Push-AppveyorArtifact appcast.xml
        }

# uncomment in stable release
#  - provider: S3
#    access_key_id:
#      secure: k68f3wMKIC5AzrfNMuC4kdPaxzvKdFVkRsietUKqc+E=
#    secret_access_key:
#      secure: IbpdpiHzGfMasaSA6uGrskE4xu9wE+HzElW7tIDOUww+ivHj+gN+mPgUHKCcV9Cn
#    bucket: sparkle.musescore.org
#    folder: testing/3/win/
#    region: us-east-1
#    set_public: true
#    artifact: appcast.xml
