name: CI_codestyle

on:
  pull_request:
    branches:
    - master
    - 4.1.0

jobs:
  codestyle:    
    runs-on: ubuntu-20.04
    steps:
    - name: Clone repository
      uses: actions/checkout@v3    
    - name: Test coding style
      run: |
        bash ./build/ci/linux/checkcodestyle.sh
