name: Collect release info

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Mode: stable, testing(alpha, beta, rc)'
        required: true
        default: 'testing'
      tag:
        description: 'Release tag (latest stable by default)'
        required: false

defaults:
  run:
    shell: bash

jobs:
  update-release-info:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Update info about the release in musescore-updates
        run: |
          S3_URL="s3://musescore-updates/feed/latest.xml"
          S3_ALL_URL="s3://musescore-updates/feed/all.xml"
          
          if [ ${{ github.event.inputs.mode }} == "testing" ]; then
            S3_URL="s3://musescore-updates/feed/latest.test.xml"
            S3_ALL_URL="s3://musescore-updates/feed/all.test.xml"
          fi

          sudo bash ./buildscripts/ci/release/make_release_info_file.sh \
            --token ${{ secrets.GITHUB_TOKEN }} \
            --repo ${{ github.repository }} \
            --release_tag ${{ github.event.inputs.tag }}

          sudo bash ./buildscripts/ci/release/push_file_to_s3.sh \
            --s3_key ${{ secrets.S3_KEY_UPDATE }} \
            --s3_secret ${{ secrets.S3_SECRET_UPDATE }} \
            --s3_url ${S3_URL} \
            --s3_bucket ${{ secrets.S3_BUCKET_UPDATE }} \
            --file_name "release_info.json"

          sudo bash ./buildscripts/ci/release/make_previous_releases_notes.sh \
            --s3_key ${{ secrets.S3_KEY_UPDATE }} \
            --s3_secret ${{ secrets.S3_SECRET_UPDATE }} \
            --s3_url ${S3_ALL_URL} \
            --s3_bucket ${{ secrets.S3_BUCKET_UPDATE }} \
            --current_file_name "release_info.json" \
            --previous_file_name "previous_releases_notes.json"
          
          sudo bash ./buildscripts/ci/release/push_file_to_s3.sh \
            --s3_key ${{ secrets.S3_KEY_UPDATE }} \
            --s3_secret ${{ secrets.S3_SECRET_UPDATE }} \
            --s3_url ${S3_ALL_URL} \
            --s3_bucket ${{ secrets.S3_BUCKET_UPDATE }} \
            --file_name "previous_releases_notes.json"