name: Collect release info

on:
  release:
    types: [ published ]

defaults:
  run:
    shell: bash

jobs:
  update-release-info:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Update info about the latest release in musescore-updates
        run: |
          sudo bash ./build/ci/release/update_latest_release_info.sh \
            --token ${{ secrets.GITHUB_TOKEN }} \
            --repo ${{ github.repository }} \
            --s3_key ${{ secrets.S3_KEY }} \
            --s3_secret ${{ secrets.S3_SECRET }} \
            --s3_url "s3://musescore-updates/feed/latest.xml" \
            --s3_bucket "s3.ultimate-guitar"
