name: CI_Run_tx2s3

on:
  pull_request:
    branches:
    - 3.x_off
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes
  workflow_dispatch:

jobs:
  tx2s3:
    runs-on: ubuntu-20.04
    steps:
    - name: "Configure workflow"
      run: |
        DO_RUN='true'
        if [ -z "${{ secrets.TRANSIFEX_USER }}" ]; then DO_RUN='false'; fi
        if [ -z "${{ secrets.TRANSIFEX_PASSWORD }}" ]; then DO_RUN='false'; fi
        if [ -z "${{ secrets.S3_KEY }}" ]; then DO_RUN='false'; fi
        if [ -z "${{ secrets.S3_SECRET }}" ]; then DO_RUN='false'; fi

        if [ $DO_RUN == 'false' ]; then
          echo "not set credentials, not possible run"
        fi  

        echo "DO_RUN=$DO_RUN" >> $GITHUB_ENV
        echo "DO_RUN: $DO_RUN"

    - name: Clone repository
      if: env.DO_RUN == 'true'
      uses: actions/checkout@v4

    - name: Setup environment
      if: env.DO_RUN == 'true'
      run: |
        sudo bash ./build/ci/tx2s3/setup.sh --tx_user ${{ secrets.TRANSIFEX_USER }} --tx_password ${{ secrets.TRANSIFEX_PASSWORD }} --s3_key ${{ secrets.S3_KEY }} --s3_secret ${{ secrets.S3_SECRET }}
    
    - name: Run tx2s3
      if: env.DO_RUN == 'true'
      run: |
        sudo bash ./build/ci/tx2s3/tx2s3.sh
        
    - name: Upload artifacts on GitHub
      if: env.DO_RUN == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: MuseScore_locale_${{ github.run_id }}
        path: ./share/locale
