name: 'Translate: lupdate source TS in repo'

on:
  workflow_dispatch:
    inputs:
      cleanup_obsolete:
        description: "Clean up obsolete strings"
        required: true
        type: boolean
        default: false
      use_qt69:
        description: 'Use Qt 6.9'
        default: 'on'
        required: false   
  schedule:
    - cron: "0 12 * * Sun"

env:
  USE_QT69: ${{ inputs.use_qt69 != '' && inputs.use_qt69 || 'on' }}        

jobs:
  lupdate:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule' || github.repository == 'musescore/MuseScore'
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Configure workflow
        run: |
          LUPDATE_ARGS=''
          if [[ "${{ github.event_name }}" == "schedule" || "${{ inputs.cleanup_obsolete }}" == "true" ]]; then
            LUPDATE_ARGS='-no-obsolete'
          fi

          echo "LUPDATE_ARGS=$LUPDATE_ARGS" | tee -a $GITHUB_ENV

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.USE_QT69 == 'on' && '6.9.1' || '6.2.4' }}
          host: "linux"
          target: "desktop"
          archives: "qttools qtbase icu"
          arch: ${{ env.USE_QT69== 'on' && 'linux_gcc_64' || 'gcc_64' }}

      - name: Run lupdate
        run: |
          bash ./tools/translations/run_lupdate.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: "Run `lupdate` with arguments `${{ env.LUPDATE_ARGS }}`"
          branch: "ci_lupdate${{github.ref_name && format('_{0}', github.ref_name) || ''}}"
          add-paths: share/locale/*
          title: "Update in-repo translation source files"
          body: "Run `lupdate` with arguments `${{ env.LUPDATE_ARGS }}`"
          labels: strings
          reviewers: cbjeukendrup
